openapi: 3.0.0
info:
  title: Customer API
  description: A simple API for managing customers
  version: 1.0.0
paths:
  /customers:
    get:
      summary: Retrieve a list of customers
      operationId: getCustomers
      responses:
        '200':
          description: A list of customers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customer'
  /customers/{customerId}:
    get:
      summary: Retrieve a single customer by ID
      operationId: getCustomerById
      parameters:
        - name: customerId
          in: path
          required: true
          description: ID of the customer to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Customer details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
components:
  schemas:
    Customer:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        email:
          type: string
