apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: petstore-api
  description: A simple API for managing a pet store
  annotations:
    backstage.io/techdocs-ref: url:https://example.com/petstore/docs
    github.com/project-slug: example-org/petstore-api
    openapi: https://petstore.example.com/v1/openapi.yaml
  tags:
    - pets
    - store
    - api
spec:
  type: openapi
  lifecycle: production
  owner: team-petstore
  system: petstore-system
  definition: |
    openapi: 3.0.0
    info:
      title: Pet Store API
      description: A simple API for managing a pet store
      version: 1.0.0
   
