apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: customer-api
  description: API for managing customers
  tags:
    - links
    - api
    - repositories
spec:
  type: openapi
  lifecycle: production
  definition: $text:'https://raw.githubusercontent.com/vivekbhu/backstage/refs/heads/main/customer1.yaml'
