apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: policy-api
  description: API for managing policies
  tags:
    - links
    - api
    - repositories
spec:
  type: openapi
  lifecycle: production
  owner: vsrivastava
  definition: $text:'https://raw.githubusercontent.com/vivekbhu/backstage/refs/heads/main/customer.yaml'
