apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: policy-api
  description: API for managing policies
  tags:
    - links
    - api
    - repositories
spec:
  type: openapi
  lifecycle: production
  owner: vsrivastava
  definition: $text:'https://gist.github.com/lenage/08964335de9064540c8c335fb849c5da'
